server:
  port: 8081
spring: 
  cloud:
    config:
      server:
        git:
          default-label: keycloak-interceptor
          uri: https://github.com/cr7kawai/microservicios-spring
          search-paths: config-data
  application:
    name: config-service
